name: expense_tracker
description: "Flutter Expense Tracker with Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

  # State Management
  provider: ^6.1.2

  # UI & Charts
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0

  # Data n else
  excel: ^4.0.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
